# Generated by Django 3.2.6 on 2021-08-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experts',
            name='level',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
